export const skillsSection = {
    id: 'skills',
    lightBg: true,
    lightText: false,
    lightTextDesc: true,
    topLine: 'Skills',
    heading1: 'Programming Languages',
    description1: '• Java',
    description2: '• C#',
    description3: '• C++',
    heading2: 'Web / Front-end Development',
    description4: '• HTML+CSS',
    description5: '• JavaScript (React + Next.js)',
    description6: '• Bootstrap, Foundation, MDBootstrap',
    heading3: 'Database',
    description7: '• MySQL',
    description8: '• PostgreSQL',
    buttonLabel: 'Projects',
    imgStart: true,
    img: require('../../images/undraw_percentages_0rur.svg').default,
    alt: 'Car',
    dark: false,
    primary: false,
    darkText: true

}