export const aboutSection = {
    id: 'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'About me ',
    headline: 'Education',
    description: '2015 - 2020 : PGHT "Akad. N. D. Zelinskii" (System Programing)',
    description2: '2020 - Present : Plovdiv University "Paisii Hilendarski" Major at Software Engineering ',
    headline2: 'Hobbies',
    hobby1: '• Cycling',
    hobby2: '• Playing guitar',
    hobby3: '• Reading',
    hobby4: '• Gaming',
    buttonLabel: 'Skills',
    imgStart: false,
    img: require('../../images/undraw_portfolio_website_lidw.svg').default,
    alt: 'aboutme',
    dark: true,
    primary: true,
    darkText: false
}
